#
# ESPHOME SONOFF BASIC V.1.1 - SW0 - LUZ ESTUDIO NEON BAR
#
# 12.05.2023 : Fix error Network not found tras upgrade a ESPHOME 2023.04.  Elimino componentes innecesarios, dejando solo binary_sensor + switch
#

substitutions:
  device_name: esphome_bas_sw0

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid_wlan
  password: !secret wifi_pwd
  manual_ip:
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0
    static_ip: 192.168.0.30

api:

# Enable logging
logger:

ota:

binary_sensor:
  - platform: status
    name: ${device_name}_status

switch:
  - platform: gpio
    name: ${device_name}
    pin: GPIO12
