#
# ESPHOME SONOFF DUAL-POW-R3 SW1 - PERSIANAS ESTUDIO - NEW VERSION
#
# https://community.home-assistant.io/t/template-cover-how-to-get-position-in-set-cover-position/191058/24
#
# https://esphome.io/cookbook/dual-r2-cover.html?highlight=sonoff+dual
#

substitutions:
  device_name: esphome_dual_sw1

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev
  
wifi:
  ssid: !secret wifi_ssid_tc
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 192.168.0.44
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0

api:

ota:

# Enable logging
logger:

binary_sensor:
- platform: gpio
  pin:
    number: GPIO10
    inverted: true
  id: button
  on_press:
    then:
      # logic for cycling through movements: open->stop->close->stop->...
      - lambda: |
          if (id(my_cover).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, check current state and either open or close cover.
            if (id(my_cover).is_fully_closed()) {
              id(my_cover).open();
              //id(my_cover).set_command_open() 
            } else {
              id(my_cover).close();
            }
          } else {
            // Cover is opening/closing. Stop it.
            id(my_cover).stop();
          }

switch:
- platform: gpio
  pin: GPIO27
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
  pin: GPIO14
  interlock: *interlock
  id: close_cover

cover:
- platform: time_based
  name: "Persiana Estudio"
  id: my_cover
  open_action:
    - switch.turn_on: open_cover
  open_duration: 17s
  close_action:
    - switch.turn_on: close_cover
  close_duration: 17s
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover
