#
# ESPHOME SONOFF POW R2 SW3 - PISCINA
#

substitutions:
  device_name: esphome_pow_sw3
  update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid_wlan
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 192.168.0.41
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0

api:

ota:

# Example configuration entry
# Disable logging over USB
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: ${device_name}_current
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: ${device_name}_voltage
      filters:
        - throttle_average: ${update_interval}
    power:
      name: ${device_name}_power
      filters:
        - throttle_average: ${update_interval}


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${device_name} boton
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: ${device_name}
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO15
      inverted: True

light:
  - platform: monochromatic
    name: ${device_name} led
    output: pow_blue_led
    id: led

